//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 04:31:30 PM CST 
//


package org.rmt2.jaxbtest;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.RMT2Base;


/**
 * <p>Java class for transaction_criteria_group complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="transaction_criteria_group">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gl_criteria" type="{}gl_criteria_type" minOccurs="0"/>
 *         &lt;element name="customer_criteria" type="{}customer_criteria_type" minOccurs="0"/>
 *         &lt;element name="creditor_criteria" type="{}creditor_criteria_type" minOccurs="0"/>
 *         &lt;element name="sales_criteria" type="{}sales_order_criteria" minOccurs="0"/>
 *         &lt;element name="purchases_criteria" type="{}purchase_order_criteria" minOccurs="0"/>
 *         &lt;element name="xact_criteria" type="{}xact_criteria_type" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "transaction_criteria_group", propOrder = {
    "glCriteria",
    "customerCriteria",
    "creditorCriteria",
    "salesCriteria",
    "purchasesCriteria",
    "xactCriteria"
})
public class TestTransactionCriteriaGroup
    extends RMT2Base
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "gl_criteria")
    protected TestGlCriteriaType glCriteria;
    @XmlElement(name = "customer_criteria")
    protected TestCustomerCriteriaType customerCriteria;
    @XmlElement(name = "creditor_criteria")
    protected TestCreditorCriteriaType creditorCriteria;
    @XmlElement(name = "sales_criteria")
    protected TestSalesOrderCriteria salesCriteria;
    @XmlElement(name = "purchases_criteria")
    protected TestPurchaseOrderCriteria purchasesCriteria;
    @XmlElement(name = "xact_criteria")
    protected TestXactCriteriaType xactCriteria;

    /**
     * Gets the value of the glCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link GlCriteriaType }
     *     
     */
    public TestGlCriteriaType getGlCriteria() {
        return glCriteria;
    }

    /**
     * Sets the value of the glCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlCriteriaType }
     *     
     */
    public void setGlCriteria(TestGlCriteriaType value) {
        this.glCriteria = value;
    }

    /**
     * Gets the value of the customerCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerCriteriaType }
     *     
     */
    public TestCustomerCriteriaType getCustomerCriteria() {
        return customerCriteria;
    }

    /**
     * Sets the value of the customerCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerCriteriaType }
     *     
     */
    public void setCustomerCriteria(TestCustomerCriteriaType value) {
        this.customerCriteria = value;
    }

    /**
     * Gets the value of the creditorCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link CreditorCriteriaType }
     *     
     */
    public TestCreditorCriteriaType getCreditorCriteria() {
        return creditorCriteria;
    }

    /**
     * Sets the value of the creditorCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditorCriteriaType }
     *     
     */
    public void setCreditorCriteria(TestCreditorCriteriaType value) {
        this.creditorCriteria = value;
    }

    /**
     * Gets the value of the salesCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link SalesOrderCriteria }
     *     
     */
    public TestSalesOrderCriteria getSalesCriteria() {
        return salesCriteria;
    }

    /**
     * Sets the value of the salesCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesOrderCriteria }
     *     
     */
    public void setSalesCriteria(TestSalesOrderCriteria value) {
        this.salesCriteria = value;
    }

    /**
     * Gets the value of the purchasesCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link PurchaseOrderCriteria }
     *     
     */
    public TestPurchaseOrderCriteria getPurchasesCriteria() {
        return purchasesCriteria;
    }

    /**
     * Sets the value of the purchasesCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link PurchaseOrderCriteria }
     *     
     */
    public void setPurchasesCriteria(TestPurchaseOrderCriteria value) {
        this.purchasesCriteria = value;
    }

    /**
     * Gets the value of the xactCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link XactCriteriaType }
     *     
     */
    public TestXactCriteriaType getXactCriteria() {
        return xactCriteria;
    }

    /**
     * Sets the value of the xactCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link XactCriteriaType }
     *     
     */
    public void setXactCriteria(TestXactCriteriaType value) {
        this.xactCriteria = value;
    }

}
