//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 04:31:30 PM CST 
//


package org.rmt2.jaxbtest;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.RMT2Base;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="header" type="{}header_type"/>
 *         &lt;element name="reply_status" type="{}reply_status_type" minOccurs="0"/>
 *         &lt;element name="zip_short" type="{}zipcode_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="zip_full" type="{}zipcode_full_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="countries" type="{}country_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="states" type="{}state_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ip_data" type="{}ip_details"/>
 *         &lt;element name="timezones" type="{}timezone_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="pagination_info" type="{}pagination_type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "replyStatus",
    "zipShort",
    "zipFull",
    "countries",
    "states",
    "ipData",
    "timezones",
    "paginationInfo"
})
@XmlRootElement(name = "PostalResponse")
public class TestPostalResponse
    extends RMT2Base
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected TestHeaderType header;
    @XmlElement(name = "reply_status")
    protected TestReplyStatusType replyStatus;
    @XmlElement(name = "zip_short")
    protected List<TestZipcodeType> zipShort;
    @XmlElement(name = "zip_full")
    protected List<TestZipcodeFullType> zipFull;
    protected List<TestCountryType> countries;
    protected List<TestStateType> states;
    @XmlElement(name = "ip_data", required = true)
    protected TestIpDetails ipData;
    protected List<TestTimezoneType> timezones;
    @XmlElement(name = "pagination_info", required = true)
    protected TestPaginationType paginationInfo;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderType }
     *     
     */
    public TestHeaderType getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderType }
     *     
     */
    public void setHeader(TestHeaderType value) {
        this.header = value;
    }

    /**
     * Gets the value of the replyStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ReplyStatusType }
     *     
     */
    public TestReplyStatusType getReplyStatus() {
        return replyStatus;
    }

    /**
     * Sets the value of the replyStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplyStatusType }
     *     
     */
    public void setReplyStatus(TestReplyStatusType value) {
        this.replyStatus = value;
    }

    /**
     * Gets the value of the zipShort property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the zipShort property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getZipShort().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ZipcodeType }
     * 
     * 
     */
    public List<TestZipcodeType> getZipShort() {
        if (zipShort == null) {
            zipShort = new ArrayList<TestZipcodeType>();
        }
        return this.zipShort;
    }

    /**
     * Gets the value of the zipFull property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the zipFull property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getZipFull().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ZipcodeFullType }
     * 
     * 
     */
    public List<TestZipcodeFullType> getZipFull() {
        if (zipFull == null) {
            zipFull = new ArrayList<TestZipcodeFullType>();
        }
        return this.zipFull;
    }

    /**
     * Gets the value of the countries property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the countries property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCountries().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CountryType }
     * 
     * 
     */
    public List<TestCountryType> getCountries() {
        if (countries == null) {
            countries = new ArrayList<TestCountryType>();
        }
        return this.countries;
    }

    /**
     * Gets the value of the states property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the states property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StateType }
     * 
     * 
     */
    public List<TestStateType> getStates() {
        if (states == null) {
            states = new ArrayList<TestStateType>();
        }
        return this.states;
    }

    /**
     * Gets the value of the ipData property.
     * 
     * @return
     *     possible object is
     *     {@link IpDetails }
     *     
     */
    public TestIpDetails getIpData() {
        return ipData;
    }

    /**
     * Sets the value of the ipData property.
     * 
     * @param value
     *     allowed object is
     *     {@link IpDetails }
     *     
     */
    public void setIpData(TestIpDetails value) {
        this.ipData = value;
    }

    /**
     * Gets the value of the timezones property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the timezones property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTimezones().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TimezoneType }
     * 
     * 
     */
    public List<TestTimezoneType> getTimezones() {
        if (timezones == null) {
            timezones = new ArrayList<TestTimezoneType>();
        }
        return this.timezones;
    }

    /**
     * Gets the value of the paginationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PaginationType }
     *     
     */
    public TestPaginationType getPaginationInfo() {
        return paginationInfo;
    }

    /**
     * Sets the value of the paginationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaginationType }
     *     
     */
    public void setPaginationInfo(TestPaginationType value) {
        this.paginationInfo = value;
    }

}
