//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.11 at 04:31:30 PM CST 
//


package org.rmt2.jaxbtest;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.rmt2.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class TestObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.rmt2.jaxb
     * 
     */
    public TestObjectFactory() {
    }

    /**
     * Create an instance of {@link PostalRequest }
     * 
     */
    public TestPostalRequest createPostalRequest() {
        return new TestPostalRequest();
    }

    /**
     * Create an instance of {@link AddressBookRequest }
     * 
     */
    public TestAddressBookRequest createAddressBookRequest() {
        return new TestAddressBookRequest();
    }

    /**
     * Create an instance of {@link HeaderType }
     * 
     */
    public TestHeaderType createHeaderType() {
        return new TestHeaderType();
    }

    /**
     * Create an instance of {@link ContactCriteriaGroup }
     * 
     */
    public TestContactCriteriaGroup createContactCriteriaGroup() {
        return new TestContactCriteriaGroup();
    }

    /**
     * Create an instance of {@link ContactDetailGroup }
     * 
     */
    public TestContactDetailGroup createContactDetailGroup() {
        return new TestContactDetailGroup();
    }

    /**
     * Create an instance of {@link AddressBookResponse }
     * 
     */
    public TestAddressBookResponse createAddressBookResponse() {
        return new TestAddressBookResponse();
    }

    /**
     * Create an instance of {@link ReplyStatusType }
     * 
     */
    public TestReplyStatusType createReplyStatusType() {
        return new TestReplyStatusType();
    }

    /**
     * Create an instance of {@link AccountingTransactionResponse }
     * 
     */
    public TestAccountingTransactionResponse createAccountingTransactionResponse() {
        return new TestAccountingTransactionResponse();
    }

    /**
     * Create an instance of {@link TransactionDetailGroup }
     * 
     */
    public TestTransactionDetailGroup createTransactionDetailGroup() {
        return new TestTransactionDetailGroup();
    }

    /**
     * Create an instance of {@link ProvinceRequest }
     * 
     */
    public TestProvinceRequest createProvinceRequest() {
        return new TestProvinceRequest();
    }

    /**
     * Create an instance of {@link OrderByType }
     * 
     */
    public TestOrderByType createOrderByType() {
        return new TestOrderByType();
    }

    /**
     * Create an instance of {@link LookupCodesResponse }
     * 
     */
    public TestLookupCodesResponse createLookupCodesResponse() {
        return new TestLookupCodesResponse();
    }

    /**
     * Create an instance of {@link CodeGroupType }
     * 
     */
    public TestCodeGroupType createCodeGroupType() {
        return new TestCodeGroupType();
    }

    /**
     * Create an instance of {@link CodeDetailType }
     * 
     */
    public TestCodeDetailType createCodeDetailType() {
        return new TestCodeDetailType();
    }

    /**
     * Create an instance of {@link ProvinceResponse }
     * 
     */
    public TestProvinceResponse createProvinceResponse() {
        return new TestProvinceResponse();
    }

    /**
     * Create an instance of {@link StateType }
     * 
     */
    public TestStateType createStateType() {
        return new TestStateType();
    }

    /**
     * Create an instance of {@link AudioVideoRequest }
     * 
     */
    public TestAudioVideoRequest createAudioVideoRequest() {
        return new TestAudioVideoRequest();
    }

    /**
     * Create an instance of {@link AudioVideoCriteria }
     * 
     */
    public TestAudioVideoCriteria createAudioVideoCriteria() {
        return new TestAudioVideoCriteria();
    }

    /**
     * Create an instance of {@link AudioVideoDetailGroup }
     * 
     */
    public TestAudioVideoDetailGroup createAudioVideoDetailGroup() {
        return new TestAudioVideoDetailGroup();
    }

    /**
     * Create an instance of {@link AudioVideoResponse }
     * 
     */
    public TestAudioVideoResponse createAudioVideoResponse() {
        return new TestAudioVideoResponse();
    }

    /**
     * Create an instance of {@link AccountingGeneralLedgerResponse }
     * 
     */
    public TestAccountingGeneralLedgerResponse createAccountingGeneralLedgerResponse() {
        return new TestAccountingGeneralLedgerResponse();
    }

    /**
     * Create an instance of {@link GlDetailGroup }
     * 
     */
    public TestGlDetailGroup createGlDetailGroup() {
        return new TestGlDetailGroup();
    }

    /**
     * Create an instance of {@link UserAuthenticationResponse }
     * 
     */
    public TestUserAuthenticationResponse createUserAuthenticationResponse() {
        return new TestUserAuthenticationResponse();
    }

    /**
     * Create an instance of {@link UserSessionType }
     * 
     */
    public TestUserSessionType createUserSessionType() {
        return new TestUserSessionType();
    }

    /**
     * Create an instance of {@link PostalResponse }
     * 
     */
    public TestPostalResponse createPostalResponse() {
        return new TestPostalResponse();
    }

    /**
     * Create an instance of {@link ZipcodeType }
     * 
     */
    public TestZipcodeType createZipcodeType() {
        return new TestZipcodeType();
    }

    /**
     * Create an instance of {@link ZipcodeFullType }
     * 
     */
    public TestZipcodeFullType createZipcodeFullType() {
        return new TestZipcodeFullType();
    }

    /**
     * Create an instance of {@link CountryType }
     * 
     */
    public TestCountryType createCountryType() {
        return new TestCountryType();
    }

    /**
     * Create an instance of {@link IpDetails }
     * 
     */
    public TestIpDetails createIpDetails() {
        return new TestIpDetails();
    }

    /**
     * Create an instance of {@link TimezoneType }
     * 
     */
    public TestTimezoneType createTimezoneType() {
        return new TestTimezoneType();
    }

    /**
     * Create an instance of {@link PaginationType }
     * 
     */
    public TestPaginationType createPaginationType() {
        return new TestPaginationType();
    }

    /**
     * Create an instance of {@link AuthenticationAppResourcesRequest }
     * 
     */
    public TestAuthenticationAppResourcesRequest createAuthenticationAppResourcesRequest() {
        return new TestAuthenticationAppResourcesRequest();
    }

    /**
     * Create an instance of {@link AuthCriteriaGroup }
     * 
     */
    public TestAuthCriteriaGroup createAuthCriteriaGroup() {
        return new TestAuthCriteriaGroup();
    }

    /**
     * Create an instance of {@link AuthDetailGroup }
     * 
     */
    public TestAuthDetailGroup createAuthDetailGroup() {
        return new TestAuthDetailGroup();
    }

    /**
     * Create an instance of {@link MultimediaRequest }
     * 
     */
    public TestMultimediaRequest createMultimediaRequest() {
        return new TestMultimediaRequest();
    }

    /**
     * Create an instance of {@link MimeContentType }
     * 
     */
    public TestMimeContentType createMimeContentType() {
        return new TestMimeContentType();
    }

    /**
     * Create an instance of {@link UserAuthenticationRequest }
     * 
     */
    public TestUserAuthenticationRequest createUserAuthenticationRequest() {
        return new TestUserAuthenticationRequest();
    }

    /**
     * Create an instance of {@link UserLoginType }
     * 
     */
    public TestUserLoginType createUserLoginType() {
        return new TestUserLoginType();
    }

    /**
     * Create an instance of {@link AccountingTransactionRequest }
     * 
     */
    public TestAccountingTransactionRequest createAccountingTransactionRequest() {
        return new TestAccountingTransactionRequest();
    }

    /**
     * Create an instance of {@link TransactionCriteriaGroup }
     * 
     */
    public TestTransactionCriteriaGroup createTransactionCriteriaGroup() {
        return new TestTransactionCriteriaGroup();
    }

    /**
     * Create an instance of {@link LookupCodesRequest }
     * 
     */
    public TestLookupCodesRequest createLookupCodesRequest() {
        return new TestLookupCodesRequest();
    }

    /**
     * Create an instance of {@link LookupCodeCriteriaType }
     * 
     */
    public TestLookupCodeCriteriaType createLookupCodeCriteriaType() {
        return new TestLookupCodeCriteriaType();
    }

    /**
     * Create an instance of {@link RSCommonReply }
     * 
     */
    public TestRSCommonReply createRSCommonReply() {
        return new TestRSCommonReply();
    }

    /**
     * Create an instance of {@link AccountingGeneralLedgerRequest }
     * 
     */
    public TestAccountingGeneralLedgerRequest createAccountingGeneralLedgerRequest() {
        return new TestAccountingGeneralLedgerRequest();
    }

    /**
     * Create an instance of {@link GlCriteriaGroup }
     * 
     */
    public TestGlCriteriaGroup createGlCriteriaGroup() {
        return new TestGlCriteriaGroup();
    }

    /**
     * Create an instance of {@link ProjectProfileRequest }
     * 
     */
    public TestProjectProfileRequest createProjectProfileRequest() {
        return new TestProjectProfileRequest();
    }

    /**
     * Create an instance of {@link ProjectCriteriaGroup }
     * 
     */
    public TestProjectCriteriaGroup createProjectCriteriaGroup() {
        return new TestProjectCriteriaGroup();
    }

    /**
     * Create an instance of {@link ProjectDetailGroup }
     * 
     */
    public TestProjectDetailGroup createProjectDetailGroup() {
        return new TestProjectDetailGroup();
    }

    /**
     * Create an instance of {@link MultimediaResponse }
     * 
     */
    public TestMultimediaResponse createMultimediaResponse() {
        return new TestMultimediaResponse();
    }

    /**
     * Create an instance of {@link AuthenticationAppResourcesResponse }
     * 
     */
    public TestAuthenticationAppResourcesResponse createAuthenticationAppResourcesResponse() {
        return new TestAuthenticationAppResourcesResponse();
    }

    /**
     * Create an instance of {@link ProjectProfileResponse }
     * 
     */
    public TestProjectProfileResponse createProjectProfileResponse() {
        return new TestProjectProfileResponse();
    }

    /**
     * Create an instance of {@link PostalRequest.PostalCriteria }
     * 
     */
    public TestPostalRequest.PostalCriteria createPostalRequestPostalCriteria() {
        return new TestPostalRequest.PostalCriteria();
    }

    /**
     * Create an instance of {@link XactItemType }
     * 
     */
    public TestXactItemType createXactItemType() {
        return new TestXactItemType();
    }

    /**
     * Create an instance of {@link CountryCriteriaType }
     * 
     */
    public TestCountryCriteriaType createCountryCriteriaType() {
        return new TestCountryCriteriaType();
    }

    /**
     * Create an instance of {@link ItemMasterStatusType }
     * 
     */
    public TestItemMasterStatusType createItemMasterStatusType() {
        return new TestItemMasterStatusType();
    }

    /**
     * Create an instance of {@link AudioVideoTrackInfo }
     * 
     */
    public TestAudioVideoTrackInfo createAudioVideoTrackInfo() {
        return new TestAudioVideoTrackInfo();
    }

    /**
     * Create an instance of {@link GlAccountType }
     * 
     */
    public TestGlAccountType createGlAccountType() {
        return new TestGlAccountType();
    }

    /**
     * Create an instance of {@link XacttypeItemType }
     * 
     */
    public TestXacttypeItemType createXacttypeItemType() {
        return new TestXacttypeItemType();
    }

    /**
     * Create an instance of {@link EmployeeCriteriaType }
     * 
     */
    public TestEmployeeCriteriaType createEmployeeCriteriaType() {
        return new TestEmployeeCriteriaType();
    }

    /**
     * Create an instance of {@link ItemCriteriaType }
     * 
     */
    public TestItemCriteriaType createItemCriteriaType() {
        return new TestItemCriteriaType();
    }

    /**
     * Create an instance of {@link CustomerActivityType }
     * 
     */
    public TestCustomerActivityType createCustomerActivityType() {
        return new TestCustomerActivityType();
    }

    /**
     * Create an instance of {@link MimeType }
     * 
     */
    public TestMimeType createMimeType() {
        return new TestMimeType();
    }

    /**
     * Create an instance of {@link AudioVideoMediaTypeLookup }
     * 
     */
    public TestAudioVideoMediaTypeLookup createAudioVideoMediaTypeLookup() {
        return new TestAudioVideoMediaTypeLookup();
    }

    /**
     * Create an instance of {@link TimezoneCriteriaType }
     * 
     */
    public TestTimezoneCriteriaType createTimezoneCriteriaType() {
        return new TestTimezoneCriteriaType();
    }

    /**
     * Create an instance of {@link XacttypeType }
     * 
     */
    public TestXacttypeType createXacttypeType() {
        return new TestXacttypeType();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public TestUserType createUserType() {
        return new TestUserType();
    }

    /**
     * Create an instance of {@link EmployeeTitleType }
     * 
     */
    public TestEmployeeTitleType createEmployeeTitleType() {
        return new TestEmployeeTitleType();
    }

    /**
     * Create an instance of {@link UserResourceAccessCriteriaType }
     * 
     */
    public TestUserResourceAccessCriteriaType createUserResourceAccessCriteriaType() {
        return new TestUserResourceAccessCriteriaType();
    }

    /**
     * Create an instance of {@link VendorItemType }
     * 
     */
    public TestVendorItemType createVendorItemType() {
        return new TestVendorItemType();
    }

    /**
     * Create an instance of {@link CommonContactType }
     * 
     */
    public TestCommonContactType createCommonContactType() {
        return new TestCommonContactType();
    }

    /**
     * Create an instance of {@link PurchaseOrderStatusHistoryType }
     * 
     */
    public TestPurchaseOrderStatusHistoryType createPurchaseOrderStatusHistoryType() {
        return new TestPurchaseOrderStatusHistoryType();
    }

    /**
     * Create an instance of {@link SalesInvoiceType }
     * 
     */
    public TestSalesInvoiceType createSalesInvoiceType() {
        return new TestSalesInvoiceType();
    }

    /**
     * Create an instance of {@link TimesheetStatusHistoryType }
     * 
     */
    public TestTimesheetStatusHistoryType createTimesheetStatusHistoryType() {
        return new TestTimesheetStatusHistoryType();
    }

    /**
     * Create an instance of {@link GlBalancetypeType }
     * 
     */
    public TestGlBalancetypeType createGlBalancetypeType() {
        return new TestGlBalancetypeType();
    }

    /**
     * Create an instance of {@link ResourceType }
     * 
     */
    public TestResourceType createResourceType() {
        return new TestResourceType();
    }

    /**
     * Create an instance of {@link BusinessType }
     * 
     */
    public TestBusinessType createBusinessType() {
        return new TestBusinessType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public TestAddressType createAddressType() {
        return new TestAddressType();
    }

    /**
     * Create an instance of {@link XactCriteriaType }
     * 
     */
    public TestXactCriteriaType createXactCriteriaType() {
        return new TestXactCriteriaType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public TestPersonType createPersonType() {
        return new TestPersonType();
    }

    /**
     * Create an instance of {@link XactCodeType }
     * 
     */
    public TestXactCodeType createXactCodeType() {
        return new TestXactCodeType();
    }

    /**
     * Create an instance of {@link ResourceExtType }
     * 
     */
    public TestResourceExtType createResourceExtType() {
        return new TestResourceExtType();
    }

    /**
     * Create an instance of {@link ProjectType }
     * 
     */
    public TestProjectType createProjectType() {
        return new TestProjectType();
    }

    /**
     * Create an instance of {@link TimesheetType }
     * 
     */
    public TestTimesheetType createTimesheetType() {
        return new TestTimesheetType();
    }

    /**
     * Create an instance of {@link TimesheetStatusType }
     * 
     */
    public TestTimesheetStatusType createTimesheetStatusType() {
        return new TestTimesheetStatusType();
    }

    /**
     * Create an instance of {@link CreditorType }
     * 
     */
    public TestCreditorType createCreditorType() {
        return new TestCreditorType();
    }

    /**
     * Create an instance of {@link StatesCriteriaType }
     * 
     */
    public TestStatesCriteriaType createStatesCriteriaType() {
        return new TestStatesCriteriaType();
    }

    /**
     * Create an instance of {@link ResourceSubtypeType }
     * 
     */
    public TestResourceSubtypeType createResourceSubtypeType() {
        return new TestResourceSubtypeType();
    }

    /**
     * Create an instance of {@link ApplicationType }
     * 
     */
    public TestApplicationType createApplicationType() {
        return new TestApplicationType();
    }

    /**
     * Create an instance of {@link PurchaseOrderType }
     * 
     */
    public TestPurchaseOrderType createPurchaseOrderType() {
        return new TestPurchaseOrderType();
    }

    /**
     * Create an instance of {@link BusinessContactCriteria }
     * 
     */
    public TestBusinessContactCriteria createBusinessContactCriteria() {
        return new TestBusinessContactCriteria();
    }

    /**
     * Create an instance of {@link AudioVideoProjectTypeLookup }
     * 
     */
    public TestAudioVideoProjectTypeLookup createAudioVideoProjectTypeLookup() {
        return new TestAudioVideoProjectTypeLookup();
    }

    /**
     * Create an instance of {@link ZipcodeCriteriaType }
     * 
     */
    public TestZipcodeCriteriaType createZipcodeCriteriaType() {
        return new TestZipcodeCriteriaType();
    }

    /**
     * Create an instance of {@link CommonXactType }
     * 
     */
    public TestCommonXactType createCommonXactType() {
        return new TestCommonXactType();
    }

    /**
     * Create an instance of {@link CreditorActivityType }
     * 
     */
    public TestCreditorActivityType createCreditorActivityType() {
        return new TestCreditorActivityType();
    }

    /**
     * Create an instance of {@link UserAppLoginCheckType }
     * 
     */
    public TestUserAppLoginCheckType createUserAppLoginCheckType() {
        return new TestUserAppLoginCheckType();
    }

    /**
     * Create an instance of {@link XactType }
     * 
     */
    public TestXactType createXactType() {
        return new TestXactType();
    }

    /**
     * Create an instance of {@link SalesOrderItemType }
     * 
     */
    public TestSalesOrderItemType createSalesOrderItemType() {
        return new TestSalesOrderItemType();
    }

    /**
     * Create an instance of {@link AudioVideoArtistInfo }
     * 
     */
    public TestAudioVideoArtistInfo createAudioVideoArtistInfo() {
        return new TestAudioVideoArtistInfo();
    }

    /**
     * Create an instance of {@link EventType }
     * 
     */
    public TestEventType createEventType() {
        return new TestEventType();
    }

    /**
     * Create an instance of {@link ResourceAccessType }
     * 
     */
    public TestResourceAccessType createResourceAccessType() {
        return new TestResourceAccessType();
    }

    /**
     * Create an instance of {@link EmployeeProjectType }
     * 
     */
    public TestEmployeeProjectType createEmployeeProjectType() {
        return new TestEmployeeProjectType();
    }

    /**
     * Create an instance of {@link UserAppRolesType }
     * 
     */
    public TestUserAppRolesType createUserAppRolesType() {
        return new TestUserAppRolesType();
    }

    /**
     * Create an instance of {@link PurchaseOrderReturnType }
     * 
     */
    public TestPurchaseOrderReturnType createPurchaseOrderReturnType() {
        return new TestPurchaseOrderReturnType();
    }

    /**
     * Create an instance of {@link IpCriteriaType }
     * 
     */
    public TestIpCriteriaType createIpCriteriaType() {
        return new TestIpCriteriaType();
    }

    /**
     * Create an instance of {@link ProjectPeriodsType }
     * 
     */
    public TestProjectPeriodsType createProjectPeriodsType() {
        return new TestProjectPeriodsType();
    }

    /**
     * Create an instance of {@link XactItemtypeType }
     * 
     */
    public TestXactItemtypeType createXactItemtypeType() {
        return new TestXactItemtypeType();
    }

    /**
     * Create an instance of {@link ClientType }
     * 
     */
    public TestClientType createClientType() {
        return new TestClientType();
    }

    /**
     * Create an instance of {@link ItemMasterItemtypeType }
     * 
     */
    public TestItemMasterItemtypeType createItemMasterItemtypeType() {
        return new TestItemMasterItemtypeType();
    }

    /**
     * Create an instance of {@link PurchaseOrderStatusType }
     * 
     */
    public TestPurchaseOrderStatusType createPurchaseOrderStatusType() {
        return new TestPurchaseOrderStatusType();
    }

    /**
     * Create an instance of {@link UserProfileCriteriaType }
     * 
     */
    public TestUserProfileCriteriaType createUserProfileCriteriaType() {
        return new TestUserProfileCriteriaType();
    }

    /**
     * Create an instance of {@link GlSubsidiaryType }
     * 
     */
    public TestGlSubsidiaryType createGlSubsidiaryType() {
        return new TestGlSubsidiaryType();
    }

    /**
     * Create an instance of {@link RoleType }
     * 
     */
    public TestRoleType createRoleType() {
        return new TestRoleType();
    }

    /**
     * Create an instance of {@link TimesheetCriteriaType }
     * 
     */
    public TestTimesheetCriteriaType createTimesheetCriteriaType() {
        return new TestTimesheetCriteriaType();
    }

    /**
     * Create an instance of {@link AudioVideoGenreLookup }
     * 
     */
    public TestAudioVideoGenreLookup createAudioVideoGenreLookup() {
        return new TestAudioVideoGenreLookup();
    }

    /**
     * Create an instance of {@link AppRoleType }
     * 
     */
    public TestAppRoleType createAppRoleType() {
        return new TestAppRoleType();
    }

    /**
     * Create an instance of {@link SalesOrderStatusHistoryType }
     * 
     */
    public TestSalesOrderStatusHistoryType createSalesOrderStatusHistoryType() {
        return new TestSalesOrderStatusHistoryType();
    }

    /**
     * Create an instance of {@link TaskType }
     * 
     */
    public TestTaskType createTaskType() {
        return new TestTaskType();
    }

    /**
     * Create an instance of {@link SalesOrderType }
     * 
     */
    public TestSalesOrderType createSalesOrderType() {
        return new TestSalesOrderType();
    }

    /**
     * Create an instance of {@link ItemMasterType }
     * 
     */
    public TestItemMasterType createItemMasterType() {
        return new TestItemMasterType();
    }

    /**
     * Create an instance of {@link EmployeetypeType }
     * 
     */
    public TestEmployeetypeType createEmployeetypeType() {
        return new TestEmployeetypeType();
    }

    /**
     * Create an instance of {@link UserAppRolesCriteriaType }
     * 
     */
    public TestUserAppRolesCriteriaType createUserAppRolesCriteriaType() {
        return new TestUserAppRolesCriteriaType();
    }

    /**
     * Create an instance of {@link FullGroupType }
     * 
     */
    public TestFullGroupType createFullGroupType() {
        return new TestFullGroupType();
    }

    /**
     * Create an instance of {@link CommonContactCriteria }
     * 
     */
    public TestCommonContactCriteria createCommonContactCriteria() {
        return new TestCommonContactCriteria();
    }

    /**
     * Create an instance of {@link SalesOrderStatusType }
     * 
     */
    public TestSalesOrderStatusType createSalesOrderStatusType() {
        return new TestSalesOrderStatusType();
    }

    /**
     * Create an instance of {@link CreditorCriteriaType }
     * 
     */
    public TestCreditorCriteriaType createCreditorCriteriaType() {
        return new TestCreditorCriteriaType();
    }

    /**
     * Create an instance of {@link ProjectTaskType }
     * 
     */
    public TestProjectTaskType createProjectTaskType() {
        return new TestProjectTaskType();
    }

    /**
     * Create an instance of {@link CreditortypeType }
     * 
     */
    public TestCreditortypeType createCreditortypeType() {
        return new TestCreditortypeType();
    }

    /**
     * Create an instance of {@link XactCategoryType }
     * 
     */
    public TestXactCategoryType createXactCategoryType() {
        return new TestXactCategoryType();
    }

    /**
     * Create an instance of {@link RecordTrackingType }
     * 
     */
    public TestRecordTrackingType createRecordTrackingType() {
        return new TestRecordTrackingType();
    }

    /**
     * Create an instance of {@link ResourcetypeType }
     * 
     */
    public TestResourcetypeType createResourcetypeType() {
        return new TestResourcetypeType();
    }

    /**
     * Create an instance of {@link LookupCodeType }
     * 
     */
    public TestLookupCodeType createLookupCodeType() {
        return new TestLookupCodeType();
    }

    /**
     * Create an instance of {@link XacttypeItemActivityType }
     * 
     */
    public TestXacttypeItemActivityType createXacttypeItemActivityType() {
        return new TestXacttypeItemActivityType();
    }

    /**
     * Create an instance of {@link GlAccounttypeType }
     * 
     */
    public TestGlAccounttypeType createGlAccounttypeType() {
        return new TestGlAccounttypeType();
    }

    /**
     * Create an instance of {@link CustomerType }
     * 
     */
    public TestCustomerType createCustomerType() {
        return new TestCustomerType();
    }

    /**
     * Create an instance of {@link AudioVideoProjectInfo }
     * 
     */
    public TestAudioVideoProjectInfo createAudioVideoProjectInfo() {
        return new TestAudioVideoProjectInfo();
    }

    /**
     * Create an instance of {@link ItemMasterStatusHistoryType }
     * 
     */
    public TestItemMasterStatusHistoryType createItemMasterStatusHistoryType() {
        return new TestItemMasterStatusHistoryType();
    }

    /**
     * Create an instance of {@link PersonContactCriteria }
     * 
     */
    public TestPersonContactCriteria createPersonContactCriteria() {
        return new TestPersonContactCriteria();
    }

    /**
     * Create an instance of {@link UserLogoutType }
     * 
     */
    public TestUserLogoutType createUserLogoutType() {
        return new TestUserLogoutType();
    }

    /**
     * Create an instance of {@link PurchaseOrderCriteria }
     * 
     */
    public TestPurchaseOrderCriteria createPurchaseOrderCriteria() {
        return new TestPurchaseOrderCriteria();
    }

    /**
     * Create an instance of {@link GlCriteriaType }
     * 
     */
    public TestGlCriteriaType createGlCriteriaType() {
        return new TestGlCriteriaType();
    }

    /**
     * Create an instance of {@link CustomerCriteriaType }
     * 
     */
    public TestCustomerCriteriaType createCustomerCriteriaType() {
        return new TestCustomerCriteriaType();
    }

    /**
     * Create an instance of {@link XactCodeGroupType }
     * 
     */
    public TestXactCodeGroupType createXactCodeGroupType() {
        return new TestXactCodeGroupType();
    }

    /**
     * Create an instance of {@link CitytypeType }
     * 
     */
    public TestCitytypeType createCitytypeType() {
        return new TestCitytypeType();
    }

    /**
     * Create an instance of {@link GlAccountcatgType }
     * 
     */
    public TestGlAccountcatgType createGlAccountcatgType() {
        return new TestGlAccountcatgType();
    }

    /**
     * Create an instance of {@link SalesOrderCriteria }
     * 
     */
    public TestSalesOrderCriteria createSalesOrderCriteria() {
        return new TestSalesOrderCriteria();
    }

    /**
     * Create an instance of {@link PurchaseOrderItemType }
     * 
     */
    public TestPurchaseOrderItemType createPurchaseOrderItemType() {
        return new TestPurchaseOrderItemType();
    }

    /**
     * Create an instance of {@link EmployeeType }
     * 
     */
    public TestEmployeeType createEmployeeType() {
        return new TestEmployeeType();
    }

    /**
     * Create an instance of {@link ResourceSubtypeCriteriaType }
     * 
     */
    public TestResourceSubtypeCriteriaType createResourceSubtypeCriteriaType() {
        return new TestResourceSubtypeCriteriaType();
    }

    /**
     * Create an instance of {@link ResourceCriteriaType }
     * 
     */
    public TestResourceCriteriaType createResourceCriteriaType() {
        return new TestResourceCriteriaType();
    }

}
