//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.09.04 at 12:52:16 PM CDT 
//


package com.api.config.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LoggerConfigPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AppConfigContextPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ContainerManagedPool" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PageLinkMax" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="PaginationPageSize" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="PollingPage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProtocolInformation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RemoteSrvcApp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RptFileExt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RptXsltPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SerialDrive" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SerialExt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SerialPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TimeoutInterval" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="WebAppMapping" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="WebAppsDir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="WebAppsDrive" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dbmsVendor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CompanyProperties">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ContactId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CompanyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ContactFirstname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ContactLastname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ContactPhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ContactEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TaxId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Website" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SystemProperties">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="environment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="soaphost" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="SaxDriver" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="EmailConfig">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Authentication" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Defaultcontent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="HostPop3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="HostSmtp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="InternalSmtpDomain" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Resourcetype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="TemplatePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="GenerateEmailConfirmation" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ConsumerMsgHandlerMappingsKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ConsumerMsgHandlerMappingsLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="XsltTransformer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ApiConfigurators">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ApiConfigurator" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="className" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="JaxbContexts">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="JaxbContext" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MessagingSystemsInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="System" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="UseJndi" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="UseAuthentication" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="InitialContextFactory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ConnectionFactory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ProviderUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="MaxConnectAttemps" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="ConnectAttemptInterval" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DestinationMappings">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Destination" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Rmt2Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="JndiName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ContainSuffix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ServiceRegistry">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Service" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ServiceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="application" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="module" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="transaction" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="destination" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="secure" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="deliveryMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "loggerConfigPath",
    "appConfigContextPath",
    "containerManagedPool",
    "pageLinkMax",
    "paginationPageSize",
    "pollingPage",
    "protocolInformation",
    "remoteSrvcApp",
    "rptFileExt",
    "rptXsltPath",
    "serialDrive",
    "serialExt",
    "serialPath",
    "timeoutInterval",
    "webAppMapping",
    "webAppsDir",
    "webAppsDrive",
    "dbmsVendor",
    "companyProperties",
    "systemProperties",
    "apiConfigurators",
    "jaxbContexts",
    "messagingSystemsInfo",
    "destinationMappings",
    "serviceRegistry"
})
@XmlRootElement(name = "AppServerConfig")
public class AppServerConfig {

    @XmlElement(name = "LoggerConfigPath", required = true)
    protected String loggerConfigPath;
    @XmlElement(name = "AppConfigContextPath", required = true)
    protected String appConfigContextPath;
    @XmlElement(name = "ContainerManagedPool", required = true)
    protected String containerManagedPool;
    @XmlElement(name = "PageLinkMax")
    protected byte pageLinkMax;
    @XmlElement(name = "PaginationPageSize")
    protected byte paginationPageSize;
    @XmlElement(name = "PollingPage", required = true)
    protected String pollingPage;
    @XmlElement(name = "ProtocolInformation", required = true)
    protected String protocolInformation;
    @XmlElement(name = "RemoteSrvcApp", required = true)
    protected String remoteSrvcApp;
    @XmlElement(name = "RptFileExt", required = true)
    protected String rptFileExt;
    @XmlElement(name = "RptXsltPath", required = true)
    protected String rptXsltPath;
    @XmlElement(name = "SerialDrive", required = true)
    protected String serialDrive;
    @XmlElement(name = "SerialExt", required = true)
    protected String serialExt;
    @XmlElement(name = "SerialPath", required = true)
    protected String serialPath;
    @XmlElement(name = "TimeoutInterval")
    protected short timeoutInterval;
    @XmlElement(name = "WebAppMapping", required = true)
    protected String webAppMapping;
    @XmlElement(name = "WebAppsDir", required = true)
    protected String webAppsDir;
    @XmlElement(name = "WebAppsDrive", required = true)
    protected String webAppsDrive;
    @XmlElement(required = true)
    protected String dbmsVendor;
    @XmlElement(name = "CompanyProperties", required = true)
    protected AppServerConfig.CompanyProperties companyProperties;
    @XmlElement(name = "SystemProperties", required = true)
    protected AppServerConfig.SystemProperties systemProperties;
    @XmlElement(name = "ApiConfigurators", required = true)
    protected AppServerConfig.ApiConfigurators apiConfigurators;
    @XmlElement(name = "JaxbContexts", required = true)
    protected AppServerConfig.JaxbContexts jaxbContexts;
    @XmlElement(name = "MessagingSystemsInfo", required = true)
    protected AppServerConfig.MessagingSystemsInfo messagingSystemsInfo;
    @XmlElement(name = "DestinationMappings", required = true)
    protected AppServerConfig.DestinationMappings destinationMappings;
    @XmlElement(name = "ServiceRegistry", required = true)
    protected AppServerConfig.ServiceRegistry serviceRegistry;

    /**
     * Gets the value of the loggerConfigPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoggerConfigPath() {
        return loggerConfigPath;
    }

    /**
     * Sets the value of the loggerConfigPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoggerConfigPath(String value) {
        this.loggerConfigPath = value;
    }

    /**
     * Gets the value of the appConfigContextPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppConfigContextPath() {
        return appConfigContextPath;
    }

    /**
     * Sets the value of the appConfigContextPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppConfigContextPath(String value) {
        this.appConfigContextPath = value;
    }

    /**
     * Gets the value of the containerManagedPool property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerManagedPool() {
        return containerManagedPool;
    }

    /**
     * Sets the value of the containerManagedPool property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerManagedPool(String value) {
        this.containerManagedPool = value;
    }

    /**
     * Gets the value of the pageLinkMax property.
     * 
     */
    public byte getPageLinkMax() {
        return pageLinkMax;
    }

    /**
     * Sets the value of the pageLinkMax property.
     * 
     */
    public void setPageLinkMax(byte value) {
        this.pageLinkMax = value;
    }

    /**
     * Gets the value of the paginationPageSize property.
     * 
     */
    public byte getPaginationPageSize() {
        return paginationPageSize;
    }

    /**
     * Sets the value of the paginationPageSize property.
     * 
     */
    public void setPaginationPageSize(byte value) {
        this.paginationPageSize = value;
    }

    /**
     * Gets the value of the pollingPage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPollingPage() {
        return pollingPage;
    }

    /**
     * Sets the value of the pollingPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPollingPage(String value) {
        this.pollingPage = value;
    }

    /**
     * Gets the value of the protocolInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtocolInformation() {
        return protocolInformation;
    }

    /**
     * Sets the value of the protocolInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtocolInformation(String value) {
        this.protocolInformation = value;
    }

    /**
     * Gets the value of the remoteSrvcApp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoteSrvcApp() {
        return remoteSrvcApp;
    }

    /**
     * Sets the value of the remoteSrvcApp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoteSrvcApp(String value) {
        this.remoteSrvcApp = value;
    }

    /**
     * Gets the value of the rptFileExt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRptFileExt() {
        return rptFileExt;
    }

    /**
     * Sets the value of the rptFileExt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRptFileExt(String value) {
        this.rptFileExt = value;
    }

    /**
     * Gets the value of the rptXsltPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRptXsltPath() {
        return rptXsltPath;
    }

    /**
     * Sets the value of the rptXsltPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRptXsltPath(String value) {
        this.rptXsltPath = value;
    }

    /**
     * Gets the value of the serialDrive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialDrive() {
        return serialDrive;
    }

    /**
     * Sets the value of the serialDrive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialDrive(String value) {
        this.serialDrive = value;
    }

    /**
     * Gets the value of the serialExt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialExt() {
        return serialExt;
    }

    /**
     * Sets the value of the serialExt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialExt(String value) {
        this.serialExt = value;
    }

    /**
     * Gets the value of the serialPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialPath() {
        return serialPath;
    }

    /**
     * Sets the value of the serialPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialPath(String value) {
        this.serialPath = value;
    }

    /**
     * Gets the value of the timeoutInterval property.
     * 
     */
    public short getTimeoutInterval() {
        return timeoutInterval;
    }

    /**
     * Sets the value of the timeoutInterval property.
     * 
     */
    public void setTimeoutInterval(short value) {
        this.timeoutInterval = value;
    }

    /**
     * Gets the value of the webAppMapping property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebAppMapping() {
        return webAppMapping;
    }

    /**
     * Sets the value of the webAppMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebAppMapping(String value) {
        this.webAppMapping = value;
    }

    /**
     * Gets the value of the webAppsDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebAppsDir() {
        return webAppsDir;
    }

    /**
     * Sets the value of the webAppsDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebAppsDir(String value) {
        this.webAppsDir = value;
    }

    /**
     * Gets the value of the webAppsDrive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebAppsDrive() {
        return webAppsDrive;
    }

    /**
     * Sets the value of the webAppsDrive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebAppsDrive(String value) {
        this.webAppsDrive = value;
    }

    /**
     * Gets the value of the dbmsVendor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbmsVendor() {
        return dbmsVendor;
    }

    /**
     * Sets the value of the dbmsVendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbmsVendor(String value) {
        this.dbmsVendor = value;
    }

    /**
     * Gets the value of the companyProperties property.
     * 
     * @return
     *     possible object is
     *     {@link AppServerConfig.CompanyProperties }
     *     
     */
    public AppServerConfig.CompanyProperties getCompanyProperties() {
        return companyProperties;
    }

    /**
     * Sets the value of the companyProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppServerConfig.CompanyProperties }
     *     
     */
    public void setCompanyProperties(AppServerConfig.CompanyProperties value) {
        this.companyProperties = value;
    }

    /**
     * Gets the value of the systemProperties property.
     * 
     * @return
     *     possible object is
     *     {@link AppServerConfig.SystemProperties }
     *     
     */
    public AppServerConfig.SystemProperties getSystemProperties() {
        return systemProperties;
    }

    /**
     * Sets the value of the systemProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppServerConfig.SystemProperties }
     *     
     */
    public void setSystemProperties(AppServerConfig.SystemProperties value) {
        this.systemProperties = value;
    }

    /**
     * Gets the value of the apiConfigurators property.
     * 
     * @return
     *     possible object is
     *     {@link AppServerConfig.ApiConfigurators }
     *     
     */
    public AppServerConfig.ApiConfigurators getApiConfigurators() {
        return apiConfigurators;
    }

    /**
     * Sets the value of the apiConfigurators property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppServerConfig.ApiConfigurators }
     *     
     */
    public void setApiConfigurators(AppServerConfig.ApiConfigurators value) {
        this.apiConfigurators = value;
    }

    /**
     * Gets the value of the jaxbContexts property.
     * 
     * @return
     *     possible object is
     *     {@link AppServerConfig.JaxbContexts }
     *     
     */
    public AppServerConfig.JaxbContexts getJaxbContexts() {
        return jaxbContexts;
    }

    /**
     * Sets the value of the jaxbContexts property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppServerConfig.JaxbContexts }
     *     
     */
    public void setJaxbContexts(AppServerConfig.JaxbContexts value) {
        this.jaxbContexts = value;
    }

    /**
     * Gets the value of the messagingSystemsInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AppServerConfig.MessagingSystemsInfo }
     *     
     */
    public AppServerConfig.MessagingSystemsInfo getMessagingSystemsInfo() {
        return messagingSystemsInfo;
    }

    /**
     * Sets the value of the messagingSystemsInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppServerConfig.MessagingSystemsInfo }
     *     
     */
    public void setMessagingSystemsInfo(AppServerConfig.MessagingSystemsInfo value) {
        this.messagingSystemsInfo = value;
    }

    /**
     * Gets the value of the destinationMappings property.
     * 
     * @return
     *     possible object is
     *     {@link AppServerConfig.DestinationMappings }
     *     
     */
    public AppServerConfig.DestinationMappings getDestinationMappings() {
        return destinationMappings;
    }

    /**
     * Sets the value of the destinationMappings property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppServerConfig.DestinationMappings }
     *     
     */
    public void setDestinationMappings(AppServerConfig.DestinationMappings value) {
        this.destinationMappings = value;
    }

    /**
     * Gets the value of the serviceRegistry property.
     * 
     * @return
     *     possible object is
     *     {@link AppServerConfig.ServiceRegistry }
     *     
     */
    public AppServerConfig.ServiceRegistry getServiceRegistry() {
        return serviceRegistry;
    }

    /**
     * Sets the value of the serviceRegistry property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppServerConfig.ServiceRegistry }
     *     
     */
    public void setServiceRegistry(AppServerConfig.ServiceRegistry value) {
        this.serviceRegistry = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ApiConfigurator" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="className" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "apiConfigurator"
    })
    public static class ApiConfigurators {

        @XmlElement(name = "ApiConfigurator")
        protected List<AppServerConfig.ApiConfigurators.ApiConfigurator> apiConfigurator;

        /**
         * Gets the value of the apiConfigurator property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the apiConfigurator property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getApiConfigurator().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AppServerConfig.ApiConfigurators.ApiConfigurator }
         * 
         * 
         */
        public List<AppServerConfig.ApiConfigurators.ApiConfigurator> getApiConfigurator() {
            if (apiConfigurator == null) {
                apiConfigurator = new ArrayList<AppServerConfig.ApiConfigurators.ApiConfigurator>();
            }
            return this.apiConfigurator;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="className" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class ApiConfigurator {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "className")
            protected String className;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the className property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClassName() {
                return className;
            }

            /**
             * Sets the value of the className property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClassName(String value) {
                this.className = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ContactId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CompanyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ContactFirstname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ContactLastname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ContactPhone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ContactEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TaxId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Website" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contactId",
        "companyName",
        "contactFirstname",
        "contactLastname",
        "contactPhone",
        "contactEmail",
        "taxId",
        "website"
    })
    public static class CompanyProperties {

        @XmlElement(name = "ContactId", required = true)
        protected String contactId;
        @XmlElement(name = "CompanyName", required = true)
        protected String companyName;
        @XmlElement(name = "ContactFirstname", required = true)
        protected String contactFirstname;
        @XmlElement(name = "ContactLastname", required = true)
        protected String contactLastname;
        @XmlElement(name = "ContactPhone", required = true)
        protected String contactPhone;
        @XmlElement(name = "ContactEmail", required = true)
        protected String contactEmail;
        @XmlElement(name = "TaxId", required = true)
        protected String taxId;
        @XmlElement(name = "Website", required = true)
        protected String website;

        /**
         * Gets the value of the contactId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactId() {
            return contactId;
        }

        /**
         * Sets the value of the contactId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactId(String value) {
            this.contactId = value;
        }

        /**
         * Gets the value of the companyName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCompanyName() {
            return companyName;
        }

        /**
         * Sets the value of the companyName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCompanyName(String value) {
            this.companyName = value;
        }

        /**
         * Gets the value of the contactFirstname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactFirstname() {
            return contactFirstname;
        }

        /**
         * Sets the value of the contactFirstname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactFirstname(String value) {
            this.contactFirstname = value;
        }

        /**
         * Gets the value of the contactLastname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactLastname() {
            return contactLastname;
        }

        /**
         * Sets the value of the contactLastname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactLastname(String value) {
            this.contactLastname = value;
        }

        /**
         * Gets the value of the contactPhone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactPhone() {
            return contactPhone;
        }

        /**
         * Sets the value of the contactPhone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactPhone(String value) {
            this.contactPhone = value;
        }

        /**
         * Gets the value of the contactEmail property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContactEmail() {
            return contactEmail;
        }

        /**
         * Sets the value of the contactEmail property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContactEmail(String value) {
            this.contactEmail = value;
        }

        /**
         * Gets the value of the taxId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTaxId() {
            return taxId;
        }

        /**
         * Sets the value of the taxId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTaxId(String value) {
            this.taxId = value;
        }

        /**
         * Gets the value of the website property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWebsite() {
            return website;
        }

        /**
         * Sets the value of the website property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWebsite(String value) {
            this.website = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Destination" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Rmt2Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="JndiName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ContainSuffix" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "destination"
    })
    public static class DestinationMappings {

        @XmlElement(name = "Destination")
        protected List<AppServerConfig.DestinationMappings.Destination> destination;

        /**
         * Gets the value of the destination property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the destination property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDestination().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AppServerConfig.DestinationMappings.Destination }
         * 
         * 
         */
        public List<AppServerConfig.DestinationMappings.Destination> getDestination() {
            if (destination == null) {
                destination = new ArrayList<AppServerConfig.DestinationMappings.Destination>();
            }
            return this.destination;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Rmt2Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="JndiName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ContainSuffix" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "rmt2Name",
            "jndiName",
            "containSuffix"
        })
        public static class Destination {

            @XmlElement(name = "Rmt2Name", required = true)
            protected String rmt2Name;
            @XmlElement(name = "JndiName", required = true)
            protected String jndiName;
            @XmlElement(name = "ContainSuffix", required = true)
            protected String containSuffix;

            /**
             * Gets the value of the rmt2Name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRmt2Name() {
                return rmt2Name;
            }

            /**
             * Sets the value of the rmt2Name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRmt2Name(String value) {
                this.rmt2Name = value;
            }

            /**
             * Gets the value of the jndiName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getJndiName() {
                return jndiName;
            }

            /**
             * Sets the value of the jndiName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setJndiName(String value) {
                this.jndiName = value;
            }

            /**
             * Gets the value of the containSuffix property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContainSuffix() {
                return containSuffix;
            }

            /**
             * Sets the value of the containSuffix property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContainSuffix(String value) {
                this.containSuffix = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="JaxbContext" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "jaxbContext"
    })
    public static class JaxbContexts {

        @XmlElement(name = "JaxbContext")
        protected List<AppServerConfig.JaxbContexts.JaxbContext> jaxbContext;

        /**
         * Gets the value of the jaxbContext property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the jaxbContext property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getJaxbContext().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AppServerConfig.JaxbContexts.JaxbContext }
         * 
         * 
         */
        public List<AppServerConfig.JaxbContexts.JaxbContext> getJaxbContext() {
            if (jaxbContext == null) {
                jaxbContext = new ArrayList<AppServerConfig.JaxbContexts.JaxbContext>();
            }
            return this.jaxbContext;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class JaxbContext {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "name")
            protected String name;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="System" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="UseJndi" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="UseAuthentication" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="InitialContextFactory" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ConnectionFactory" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ProviderUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="MaxConnectAttemps" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="ConnectAttemptInterval" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "system"
    })
    public static class MessagingSystemsInfo {

        @XmlElement(name = "System")
        protected List<AppServerConfig.MessagingSystemsInfo.System> system;

        /**
         * Gets the value of the system property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the system property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSystem().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AppServerConfig.MessagingSystemsInfo.System }
         * 
         * 
         */
        public List<AppServerConfig.MessagingSystemsInfo.System> getSystem() {
            if (system == null) {
                system = new ArrayList<AppServerConfig.MessagingSystemsInfo.System>();
            }
            return this.system;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="UseJndi" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="UseAuthentication" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="InitialContextFactory" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ConnectionFactory" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ProviderUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="MaxConnectAttemps" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="ConnectAttemptInterval" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "useJndi",
            "useAuthentication",
            "initialContextFactory",
            "connectionFactory",
            "providerUrl",
            "userId",
            "password",
            "maxConnectAttemps",
            "connectAttemptInterval"
        })
        public static class System {

            @XmlElement(name = "Name", required = true)
            protected String name;
            @XmlElement(name = "UseJndi", required = true)
            protected String useJndi;
            @XmlElement(name = "UseAuthentication", required = true)
            protected String useAuthentication;
            @XmlElement(name = "InitialContextFactory", required = true)
            protected String initialContextFactory;
            @XmlElement(name = "ConnectionFactory", required = true)
            protected String connectionFactory;
            @XmlElement(name = "ProviderUrl", required = true)
            protected String providerUrl;
            @XmlElement(name = "UserId", required = true)
            protected String userId;
            @XmlElement(name = "Password", required = true)
            protected String password;
            @XmlElement(name = "MaxConnectAttemps")
            protected byte maxConnectAttemps;
            @XmlElement(name = "ConnectAttemptInterval")
            protected short connectAttemptInterval;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the useJndi property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUseJndi() {
                return useJndi;
            }

            /**
             * Sets the value of the useJndi property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUseJndi(String value) {
                this.useJndi = value;
            }

            /**
             * Gets the value of the useAuthentication property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUseAuthentication() {
                return useAuthentication;
            }

            /**
             * Sets the value of the useAuthentication property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUseAuthentication(String value) {
                this.useAuthentication = value;
            }

            /**
             * Gets the value of the initialContextFactory property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInitialContextFactory() {
                return initialContextFactory;
            }

            /**
             * Sets the value of the initialContextFactory property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInitialContextFactory(String value) {
                this.initialContextFactory = value;
            }

            /**
             * Gets the value of the connectionFactory property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getConnectionFactory() {
                return connectionFactory;
            }

            /**
             * Sets the value of the connectionFactory property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setConnectionFactory(String value) {
                this.connectionFactory = value;
            }

            /**
             * Gets the value of the providerUrl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProviderUrl() {
                return providerUrl;
            }

            /**
             * Sets the value of the providerUrl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProviderUrl(String value) {
                this.providerUrl = value;
            }

            /**
             * Gets the value of the userId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUserId() {
                return userId;
            }

            /**
             * Sets the value of the userId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUserId(String value) {
                this.userId = value;
            }

            /**
             * Gets the value of the password property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPassword() {
                return password;
            }

            /**
             * Sets the value of the password property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPassword(String value) {
                this.password = value;
            }

            /**
             * Gets the value of the maxConnectAttemps property.
             * 
             */
            public byte getMaxConnectAttemps() {
                return maxConnectAttemps;
            }

            /**
             * Sets the value of the maxConnectAttemps property.
             * 
             */
            public void setMaxConnectAttemps(byte value) {
                this.maxConnectAttemps = value;
            }

            /**
             * Gets the value of the connectAttemptInterval property.
             * 
             */
            public short getConnectAttemptInterval() {
                return connectAttemptInterval;
            }

            /**
             * Sets the value of the connectAttemptInterval property.
             * 
             */
            public void setConnectAttemptInterval(short value) {
                this.connectAttemptInterval = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Service" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ServiceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="application" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="module" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="transaction" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="destination" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="secure" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="deliveryMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "service"
    })
    public static class ServiceRegistry {

        @XmlElement(name = "Service")
        protected List<AppServerConfig.ServiceRegistry.Service> service;

        /**
         * Gets the value of the service property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the service property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getService().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AppServerConfig.ServiceRegistry.Service }
         * 
         * 
         */
        public List<AppServerConfig.ServiceRegistry.Service> getService() {
            if (service == null) {
                service = new ArrayList<AppServerConfig.ServiceRegistry.Service>();
            }
            return this.service;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ServiceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="application" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="module" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="transaction" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="destination" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="secure" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="deliveryMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "serviceType",
            "application",
            "module",
            "transaction",
            "destination",
            "description",
            "secure",
            "host",
            "deliveryMode"
        })
        public static class Service {

            @XmlElement(name = "Name", required = true)
            protected String name;
            @XmlElement(name = "ServiceType", required = true)
            protected String serviceType;
            @XmlElement(required = true)
            protected String application;
            @XmlElement(required = true)
            protected String module;
            @XmlElement(required = true)
            protected String transaction;
            @XmlElement(required = true)
            protected String destination;
            @XmlElement(required = true)
            protected String description;
            @XmlElement(required = true)
            protected String secure;
            @XmlElement(required = true)
            protected String host;
            @XmlElement(required = true)
            protected String deliveryMode;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the serviceType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getServiceType() {
                return serviceType;
            }

            /**
             * Sets the value of the serviceType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setServiceType(String value) {
                this.serviceType = value;
            }

            /**
             * Gets the value of the application property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getApplication() {
                return application;
            }

            /**
             * Sets the value of the application property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setApplication(String value) {
                this.application = value;
            }

            /**
             * Gets the value of the module property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getModule() {
                return module;
            }

            /**
             * Sets the value of the module property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setModule(String value) {
                this.module = value;
            }

            /**
             * Gets the value of the transaction property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTransaction() {
                return transaction;
            }

            /**
             * Sets the value of the transaction property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTransaction(String value) {
                this.transaction = value;
            }

            /**
             * Gets the value of the destination property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDestination() {
                return destination;
            }

            /**
             * Sets the value of the destination property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDestination(String value) {
                this.destination = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the secure property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSecure() {
                return secure;
            }

            /**
             * Sets the value of the secure property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSecure(String value) {
                this.secure = value;
            }

            /**
             * Gets the value of the host property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHost() {
                return host;
            }

            /**
             * Sets the value of the host property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHost(String value) {
                this.host = value;
            }

            /**
             * Gets the value of the deliveryMode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDeliveryMode() {
                return deliveryMode;
            }

            /**
             * Sets the value of the deliveryMode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDeliveryMode(String value) {
                this.deliveryMode = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="environment" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="soaphost" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *         &lt;element name="SaxDriver" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="EmailConfig">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Authentication" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Defaultcontent" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="HostPop3" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="HostSmtp" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="InternalSmtpDomain" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Resourcetype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="TemplatePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="GenerateEmailConfirmation" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ConsumerMsgHandlerMappingsKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ConsumerMsgHandlerMappingsLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="XsltTransformer" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "environment",
        "soaphost",
        "saxDriver",
        "emailConfig",
        "consumerMsgHandlerMappingsKey",
        "consumerMsgHandlerMappingsLocation",
        "xsltTransformer"
    })
    public static class SystemProperties {

        @XmlElement(required = true)
        protected String environment;
        @XmlElement(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String soaphost;
        @XmlElement(name = "SaxDriver", required = true)
        protected String saxDriver;
        @XmlElement(name = "EmailConfig", required = true)
        protected AppServerConfig.SystemProperties.EmailConfig emailConfig;
        @XmlElement(name = "ConsumerMsgHandlerMappingsKey", required = true)
        protected String consumerMsgHandlerMappingsKey;
        @XmlElement(name = "ConsumerMsgHandlerMappingsLocation", required = true)
        protected String consumerMsgHandlerMappingsLocation;
        @XmlElement(name = "XsltTransformer", required = true)
        protected String xsltTransformer;

        /**
         * Gets the value of the environment property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEnvironment() {
            return environment;
        }

        /**
         * Sets the value of the environment property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEnvironment(String value) {
            this.environment = value;
        }

        /**
         * Gets the value of the soaphost property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSoaphost() {
            return soaphost;
        }

        /**
         * Sets the value of the soaphost property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSoaphost(String value) {
            this.soaphost = value;
        }

        /**
         * Gets the value of the saxDriver property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSaxDriver() {
            return saxDriver;
        }

        /**
         * Sets the value of the saxDriver property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSaxDriver(String value) {
            this.saxDriver = value;
        }

        /**
         * Gets the value of the emailConfig property.
         * 
         * @return
         *     possible object is
         *     {@link AppServerConfig.SystemProperties.EmailConfig }
         *     
         */
        public AppServerConfig.SystemProperties.EmailConfig getEmailConfig() {
            return emailConfig;
        }

        /**
         * Sets the value of the emailConfig property.
         * 
         * @param value
         *     allowed object is
         *     {@link AppServerConfig.SystemProperties.EmailConfig }
         *     
         */
        public void setEmailConfig(AppServerConfig.SystemProperties.EmailConfig value) {
            this.emailConfig = value;
        }

        /**
         * Gets the value of the consumerMsgHandlerMappingsKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConsumerMsgHandlerMappingsKey() {
            return consumerMsgHandlerMappingsKey;
        }

        /**
         * Sets the value of the consumerMsgHandlerMappingsKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConsumerMsgHandlerMappingsKey(String value) {
            this.consumerMsgHandlerMappingsKey = value;
        }

        /**
         * Gets the value of the consumerMsgHandlerMappingsLocation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConsumerMsgHandlerMappingsLocation() {
            return consumerMsgHandlerMappingsLocation;
        }

        /**
         * Sets the value of the consumerMsgHandlerMappingsLocation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConsumerMsgHandlerMappingsLocation(String value) {
            this.consumerMsgHandlerMappingsLocation = value;
        }

        /**
         * Gets the value of the xsltTransformer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getXsltTransformer() {
            return xsltTransformer;
        }

        /**
         * Sets the value of the xsltTransformer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setXsltTransformer(String value) {
            this.xsltTransformer = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Authentication" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Defaultcontent" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="HostPop3" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="HostSmtp" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="InternalSmtpDomain" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Resourcetype" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="TemplatePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="GenerateEmailConfirmation" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "authentication",
            "defaultcontent",
            "hostPop3",
            "hostSmtp",
            "internalSmtpDomain",
            "userId",
            "password",
            "resourcetype",
            "templatePath",
            "generateEmailConfirmation"
        })
        public static class EmailConfig {

            @XmlElement(name = "Authentication", required = true)
            protected String authentication;
            @XmlElement(name = "Defaultcontent", required = true)
            protected String defaultcontent;
            @XmlElement(name = "HostPop3", required = true)
            protected String hostPop3;
            @XmlElement(name = "HostSmtp", required = true)
            protected String hostSmtp;
            @XmlElement(name = "InternalSmtpDomain", required = true)
            protected String internalSmtpDomain;
            @XmlElement(name = "UserId", required = true)
            protected String userId;
            @XmlElement(name = "Password", required = true)
            protected String password;
            @XmlElement(name = "Resourcetype", required = true)
            protected String resourcetype;
            @XmlElement(name = "TemplatePath", required = true)
            protected String templatePath;
            @XmlElement(name = "GenerateEmailConfirmation", defaultValue = "true")
            protected boolean generateEmailConfirmation;

            /**
             * Gets the value of the authentication property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAuthentication() {
                return authentication;
            }

            /**
             * Sets the value of the authentication property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAuthentication(String value) {
                this.authentication = value;
            }

            /**
             * Gets the value of the defaultcontent property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDefaultcontent() {
                return defaultcontent;
            }

            /**
             * Sets the value of the defaultcontent property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDefaultcontent(String value) {
                this.defaultcontent = value;
            }

            /**
             * Gets the value of the hostPop3 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHostPop3() {
                return hostPop3;
            }

            /**
             * Sets the value of the hostPop3 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHostPop3(String value) {
                this.hostPop3 = value;
            }

            /**
             * Gets the value of the hostSmtp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHostSmtp() {
                return hostSmtp;
            }

            /**
             * Sets the value of the hostSmtp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHostSmtp(String value) {
                this.hostSmtp = value;
            }

            /**
             * Gets the value of the internalSmtpDomain property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInternalSmtpDomain() {
                return internalSmtpDomain;
            }

            /**
             * Sets the value of the internalSmtpDomain property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInternalSmtpDomain(String value) {
                this.internalSmtpDomain = value;
            }

            /**
             * Gets the value of the userId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUserId() {
                return userId;
            }

            /**
             * Sets the value of the userId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUserId(String value) {
                this.userId = value;
            }

            /**
             * Gets the value of the password property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPassword() {
                return password;
            }

            /**
             * Sets the value of the password property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPassword(String value) {
                this.password = value;
            }

            /**
             * Gets the value of the resourcetype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getResourcetype() {
                return resourcetype;
            }

            /**
             * Sets the value of the resourcetype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setResourcetype(String value) {
                this.resourcetype = value;
            }

            /**
             * Gets the value of the templatePath property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTemplatePath() {
                return templatePath;
            }

            /**
             * Sets the value of the templatePath property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTemplatePath(String value) {
                this.templatePath = value;
            }

            /**
             * Gets the value of the generateEmailConfirmation property.
             * 
             */
            public boolean isGenerateEmailConfirmation() {
                return generateEmailConfirmation;
            }

            /**
             * Sets the value of the generateEmailConfirmation property.
             * 
             */
            public void setGenerateEmailConfirmation(boolean value) {
                this.generateEmailConfirmation = value;
            }

        }

    }

}
