//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.09 at 07:38:05 PM CST 
//


package com.api.config.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.api.config.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.api.config.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AppServerConfig }
     * 
     */
    public AppServerConfig createAppServerConfig() {
        return new AppServerConfig();
    }

    /**
     * Create an instance of {@link AppServerConfig.ServiceRegistry }
     * 
     */
    public AppServerConfig.ServiceRegistry createAppServerConfigServiceRegistry() {
        return new AppServerConfig.ServiceRegistry();
    }

    /**
     * Create an instance of {@link AppServerConfig.DestinationMappings }
     * 
     */
    public AppServerConfig.DestinationMappings createAppServerConfigDestinationMappings() {
        return new AppServerConfig.DestinationMappings();
    }

    /**
     * Create an instance of {@link AppServerConfig.MessagingSystemsInfo }
     * 
     */
    public AppServerConfig.MessagingSystemsInfo createAppServerConfigMessagingSystemsInfo() {
        return new AppServerConfig.MessagingSystemsInfo();
    }

    /**
     * Create an instance of {@link AppServerConfig.JaxbContexts }
     * 
     */
    public AppServerConfig.JaxbContexts createAppServerConfigJaxbContexts() {
        return new AppServerConfig.JaxbContexts();
    }

    /**
     * Create an instance of {@link AppServerConfig.ApiConfigurators }
     * 
     */
    public AppServerConfig.ApiConfigurators createAppServerConfigApiConfigurators() {
        return new AppServerConfig.ApiConfigurators();
    }

    /**
     * Create an instance of {@link AppServerConfig.SystemProperties }
     * 
     */
    public AppServerConfig.SystemProperties createAppServerConfigSystemProperties() {
        return new AppServerConfig.SystemProperties();
    }

    /**
     * Create an instance of {@link AppServerConfig.ServiceRegistry.Service }
     * 
     */
    public AppServerConfig.ServiceRegistry.Service createAppServerConfigServiceRegistryService() {
        return new AppServerConfig.ServiceRegistry.Service();
    }

    /**
     * Create an instance of {@link AppServerConfig.DestinationMappings.Destination }
     * 
     */
    public AppServerConfig.DestinationMappings.Destination createAppServerConfigDestinationMappingsDestination() {
        return new AppServerConfig.DestinationMappings.Destination();
    }

    /**
     * Create an instance of {@link AppServerConfig.MessagingSystemsInfo.System }
     * 
     */
    public AppServerConfig.MessagingSystemsInfo.System createAppServerConfigMessagingSystemsInfoSystem() {
        return new AppServerConfig.MessagingSystemsInfo.System();
    }

    /**
     * Create an instance of {@link AppServerConfig.JaxbContexts.JaxbContext }
     * 
     */
    public AppServerConfig.JaxbContexts.JaxbContext createAppServerConfigJaxbContextsJaxbContext() {
        return new AppServerConfig.JaxbContexts.JaxbContext();
    }

    /**
     * Create an instance of {@link AppServerConfig.ApiConfigurators.ApiConfigurator }
     * 
     */
    public AppServerConfig.ApiConfigurators.ApiConfigurator createAppServerConfigApiConfiguratorsApiConfigurator() {
        return new AppServerConfig.ApiConfigurators.ApiConfigurator();
    }

    /**
     * Create an instance of {@link AppServerConfig.SystemProperties.EmailConfig }
     * 
     */
    public AppServerConfig.SystemProperties.EmailConfig createAppServerConfigSystemPropertiesEmailConfig() {
        return new AppServerConfig.SystemProperties.EmailConfig();
    }

}
